# SPDX-FileCopyrightText: © 2024 Jeffrey C. Ollie
# SPDX-License-Identifier: MIT

name: Publish docs

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: nixos
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build docs
        run: nix develop -c zig build docs

      - name: Publish docs
        uses: actions/git-pages@v2
        with:
          site: https://git.ocjtech.us/jeff/zig-notmuch
          token: ${{ forge.token }}
          source: zig-out/docs
