# SPDX-FileCopyrightText: © 2024 Jeffrey C. Ollie
# SPDX-License-Identifier: MIT

name: Publish docs

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: nixos
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up cache
        uses: https://git.ocjtech.us/jeff/attic-cache@6fc49fd7a40bb6c54cb5967727d869ac79cdeb3f # v0.0.12
        with:
          server: ${{ vars.ATTIC_SERVER }}
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          token: ${{ secrets.ATTIC_TOKEN }}
          cache: ${{ vars.ATTIC_CACHE }}

      - name: Build docs
        run: nix develop -c zig build docs

      - name: Publish docs
        run: nix develop -c git-pages-cli https://zig-notmuch.jeff.ocj.page --server ocj.page --token ${{ forge.token }} --upload-dir zig-out/docs
