name: Deploy docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:


concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: build docs
        run: |
          zig build-lib -femit-docs src/notmuch.zig
      - name: upload pages artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: deploy to github pages
        uses: action/deploy-pages@v4
        
      
